name: belajar_dart_library
description: This is library from PZN
version: 1.5.0
homepage: https://www.tiogantengsedunia.com
repository: https://github.com/dwitio/belajar_dart_library

environment:
  sdk: '>=2.16.2 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
